>Human_KIF11
------------------------------------------------------VQENIQ
QKSKDIVNKMTFHSQKFCADSD----GFSQELRNFNQEGT--KLVEESVKHSDKL-----
---NGNLEKISQETEQRCESLNTRTVYFSEQWVSSLNEREQELHNLLEVVSQCCEASSSD
ITEKSDGRKAAHEKQHNIF--LDQMTIDEDKLIAQNLELNETIK-IGLTKLNCFLEQDLK
LDIPTGTTPQRKSYLYPSTLVRTEPREHLLDQLKRKQPELLMMLNCSENNKEETIPDVDV
EEAVLGQYTEEPLSQEPSVDAGVDCSSIGGVPFFQHKKSHGKDKE---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>Mallard_KIF11
RGEDEKGIPVRVALRCRPLVPKETSEGCQXCLSFVPGEPQVVVGSD--------KVFSYD
FVFXPTVXQEEVFNTXVAPLVRGIFKGYNATVIAYGQTGSGKTYSMGGAYTASQEH----
DPSVGIIP----------------------------------------------------
----------------------------------RVINAAISGEGSGG------------
-------------------------XDWGI------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>RedGrouse_KIF11
------------------------------------------------------QTFRFD
YAFDETAPNEMVYRFTARPLVETIFERGMATCFAYGQTGSGKTHTMGGDFSGKNQ-----
DCSKGIYALAARDVFLMLKKPNYKKLELQVY-ATFFEIYSGKVFDLL------------N
RKTKLRVLEDG--KQQVQVVGLQEREVKCVEDVLKLIEIGNSCRTSGQTSANAH------
--------SSRSHAVFQIIL----RRKGKLH-------GKFSLIDLAGNERGADTSSADR
QTRLEGAEINKSLLALKECIRAL----GRNKPHTPFRASKLTQV----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>ZebraFinch_KIF11
--KSKSSESVRVVVRCRPMNSKEQTASYEKVVNVDVKLGQVSVKNPRGSSHELPKTFTFD
AVYDWNSKQVELYDETFRPLVDSVLQGFNGTIFAYGQTGTGKTYTMEGVRGDPEK-----
---RGVIPNSFDHIFTHISRSQNQ--QYLVR-ASYLEIYQEEIRDLL----------SKD
QSKRLELKERP--DTGVFVKDLTTIVTKSVKEIEHIMNLGNQNRSVGATNMNEH------
--------SSRSHAIFQITI---ECSELGLD-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>GallusGallus
------------------------------------------------------------
--FRAQAKQIDVYRSVVCPILDEVIMGYNCTVFAYGQTGTGKTFTMEGERSPNEEYTWEE
DPLAGIIPRTLHQIFEKLTENGT---EFSVK-VSLLEIYNEELFDLL--------NPAPD
VGERLQMFDDPRNKRGVIIKGLEEVTVHNKNEVYQILERGAAKRTTAATYMNAY------
--------SSRSHSVFSITI---HMKETTVDGEELVKIGKLNLVDLAGSENIGRSGAVDK
RAREAGN-INQSLLTLGRVISAL----VERAPAYSIQES---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>SocietyFinch_KIF11
------------------------------------------------------------
-------------------------------------DGT--------------------
--------------------------EFSVK-VSLLEIYNEELFDLL--------NPTPD
VGERLQMFDDPRNKRGVIIKGLEEVTVHNKNQVYQILERGAAKRTTAATYMNAY------
--------SSRSHSVFSITI---HMKETTVDGEELVKIGKLNLVDLAGSENIGRSGAVDK
RAREAGN-INQSLLTLGRVITAL----VERAPHIPYRESKLTRILQDSLGGRTKTSIIAT
ISPASINLEETLSTLEYAHRAKNIMNKPEVNQKLTKKA----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>WhiteSparrow_KIF11
-KKEEKGKNIQVVVRCRPFNASELKVSSYAVVDCDQARKEVSIRTGGVTDKSSRKTYTFD
MVFGAQAKQIDVYRSVVCPILDEVIMGYNCTVFAYGQTGTGKTFTMEGERSPNEEYTWEE
DPLAGIIPRTLHQIFEKLTENGT---EFSVK-VSLLEIYNEELFDLL--------NPTPD
VGERLQMFDDPRNKRGVIIKGLEEVTVHNKNQVYQILERGAAKRTTAATYMNAY------
--------SSRSHSVFSITI---HMKETTVDGEELVKIGKLNLVDLAGSENIGRSGAVDK
RAREAGN-INQSLLTLGRVITAL----VERAPHIPYRESKLTRILQDSLGGRTKTSIIAT
ISPASVNLEETLSTLEYAHRAKNIMNKPEVNQKLTKKALIKEYTEEIERLKRDLAAAREK
NGVYISAENYEALNGKLTVQEEQITEYIDKISVMEEEVKRVTELFRVSKNELEQCKTDLQ
IKEKELEETQKDLQETKVQLAEEEYVVSVLESTEQELHDTASQLLTTVEETTRDVSGLHA
KLERKRAVDQHNAAVQNTFAGQMNASFSKIQDSITENSLKQQQMLTYYTNCIGDLLSTSS
STADMFASVVSASFACLKELVSTEVSHISEKITQHENLSLDCKAELLRLIEEHQTGLGRA
VNSLTPMVEFVLGLNCQFQSNMKKYSAVADQMEDHKKEMDTFFADLSLTLKKIQEQTAGG
FAQLQHNCDSLKEEVEMMRLAHRKSAAELMSSLQSQLDLFAQETQKSLTDVLTRNGSLKT
TITAMQENVHLKTTDLVSSTNSNHNKFAASLDNFSQELRSINAENKAMLEESNDHCQHLL
TNLKNVAQHTNTWGEFTTAQMVNFTNQHLLSFKDEKQQFQYLQKKNEENCDQAIAEIADH
IGSQKAAEEKVLNGLLDQIKVDQEILVEQKLALREQVQHGLTQVNGFLQEDLKVDVPTGT
TPQRKDYSYPVTLVRTEPRQLLLEQLRQKQPNLDAMLSSVGKEMEDSAGQDLLEEGVLQE
PSESLACDKYSMDTNVYCHTNGGIPFFQHKRSLKKGKENKSAAPLENKMEDMTEELLQKS
KHPLR
